version: "3"
services:
  database:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=local_db
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_pass
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_data_local:/var/lib/postgresql/data/
volumes:
  pg_data_local:
